name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build artifact
        path: |
          /home/runner/work/DKCoins-Reloaded/DKCoins-Reloaded/coinsystem-spigot/target/*.jar
          /home/runner/work/DKCoins-Reloaded/DKCoins-Reloaded/coinsystem-bungeecord/target/*.jar
          /home/runner/work/DKCoins-Reloaded/DKCoins-Reloaded/coinsystem-tools-spigot-coinbooster/target/*.jar
